version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_app
    ports:
      - '8181:8080'
    environment:
      - DB_URL=jdbc:postgresql://db_15:5432/bankcards
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db_15
      - redis

  db_15:
    image: postgres:15
    container_name: bankcard_db
    ports:
      - '15432:5432'
    environment:
      POSTGRES_DB: bankcards
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7.0-alpine
    container_name: redis
    ports:
      - '6379:6379'
    deploy:
      replicas: 1

volumes:
  pgdata: